# Generated by Django 2.0.8 on 2018-11-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyblog', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User_info',
        ),
    ]
