# Generated by Django 2.0.8 on 2018-11-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyblog', '0003_auto_20181124_1633'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_info',
            new_name='User_Infos',
        ),
    ]
