# Generated by Django 2.0.8 on 2018-11-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyblog', '0005_auto_20181124_1643'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_infos',
            table='user_infos',
        ),
    ]
